name: Check
on:
- push
jobs:
  build:
    runs-on: ubuntu-latest
    container: tsl0922/musl-cross
    steps:
    - uses: actions/checkout@v2
    - name: install deps
      run: |
        apk add make gcc musl-dev
    - name: make
      run: |
        for p in i386 x86_64 aarch64 arm armhf mips mipsel; do
          make DEBUG=0 STATIC=1 STRIP=1
        done
    - name: irc notice
      uses: Gottox/irc-message-action@v2
      if: failure()
      with:
        channel: "Gottox"
        nickname: gh-gottox
        message: "https://github.com/${{ github.repository }} failed on push ${{ github.event.compare }}"
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v') && success()
      with:
        files: |
          autohup
